sqlcmd -d SceneSwarm01 -i 01_CreateSchemas.sql
sqlcmd -d SceneSwarm01 -i 02_CreateConstantTables.sql
sqlcmd -d SceneSwarm01 -i 03_CreateLocationTables.sql
sqlcmd -d SceneSwarm01 -i 04_CreateEmployeeTables.sql
sqlcmd -d SceneSwarm01 -i 05_CreateSSUserAndSSAdminTables.sql
sqlcmd -d SceneSwarm01 -i 06_CreateAddressAndVenueTables.sql
sqlcmd -d SceneSwarm01 -i 07_CreateEventTables.sql
sqlcmd -d SceneSwarm01 -i 08_CreateArtistTables.sql
sqlcmd -d SceneSwarm01 -i 09_CreateBeerTables.sql
sqlcmd -d SceneSwarm01 -i 10_CreateWineTables.sql
sqlcmd -d SceneSwarm01 -i 11_CreateLiquorTables.sql
sqlcmd -d SceneSwarm01 -i 12_CreateCiderTables.sql
sqlcmd -d SceneSwarm01 -i 13_CreateMeadTables.sql
sqlcmd -d SceneSwarm01 -i 14_CreateSeltzerTables.sql