sqlcmd -d SceneSwarm -i 01_CreateSchemas.sql
sqlcmd -d SceneSwarm -i 02_CreateConstantTables.sql
sqlcmd -d SceneSwarm -i 03_CreateLocationTables.sql
sqlcmd -d SceneSwarm -i 04_CreateEmployeeTables.sql
sqlcmd -d SceneSwarm -i 05_CreateSSUserAndSSAdminTables.sql
sqlcmd -d SceneSwarm -i 06_CreateAddressAndVenueTables.sql
sqlcmd -d SceneSwarm -i 07_CreateEventTables.sql
sqlcmd -d SceneSwarm -i 08_CreateArtistTables.sql
sqlcmd -d SceneSwarm -i 09_CreateBeerTables.sql
sqlcmd -d SceneSwarm -i 10_CreateWineTables.sql
sqlcmd -d SceneSwarm -i 11_CreateLiquorTables.sql
sqlcmd -d SceneSwarm -i 12_CreateCiderTables.sql
sqlcmd -d SceneSwarm -i 13_CreateMeadTables.sql
sqlcmd -d SceneSwarm -i 14_CreateSeltzerTables.sql