--
USE SceneSwarm01

CREATE TABLE ref.EventTypesSS(
	EventTypeID INT NOT NULL
		CONSTRAINT PK_EventTypeID
		PRIMARY KEY IDENTITY
	,EventType NVARCHAR(255) NULL	
	,CreatedBy INT NOT NULL
		CONSTRAINT FK_EventTypesSSID_CreatedBy
		REFERENCES hr.Employees(EmployeeID)
	,CreatedDate DATETIME NOT NULL
		CONSTRAINT DF_EventTypesSSID_CreatedDate
		DEFAULT GETDATE()
)

CREATE TABLE dbo.EventsSS(
	EventID INT NOT NULL
		CONSTRAINT PK_EventID
		PRIMARY KEY IDENTITY
	,EventTypeID INT NOT NULL
		CONSTRAINT FK_EventsSS_EventTypeID
		REFERENCES ref.EventTypesSS(EventTypeID)
	,EventDate DATETIME NOT NULL
	,EventTime DATETIME
	,EventVenueID INT NULL
		CONSTRAINT FK_EventsSS_EventVenueID
		REFERENCES dbo.Venues(VenueID)
	,CreatedDate DATETIME NOT NULL
		CONSTRAINT DF_EventsSS_CreatedDate
		DEFAULT GETDATE()
)

/*

DROP TABLE dbo.EventsSS
DROP TABLE ref.EventTypesSS

*/