--
USE SceneSwarm01

CREATE TABLE ref.BeerFamily(
	BeerFamilyID INT NOT NULL
		CONSTRAINT PK_BeerFamily
		PRIMARY KEY IDENTITY
	,BeerFamily NVARCHAR(255) NOT NULL
	)

CREATE TABLE ref.BeerType(
	BeerTypeID INT NOT NULL
		CONSTRAINT PK_BeerType
		PRIMARY KEY IDENTITY
	,BeerType NVARCHAR(255) NOT NULL
	,BeerFamilyID INT NOT NULL
		CONSTRAINT FK_BeerType_BeerFamilyID
		REFERENCES ref.BeerFamily(BeerFamilyID)
	)

CREATE TABLE dbo.Brewery(
	BreweryID INT NOT NULL
		CONSTRAINT PK_Brewery
		PRIMARY KEY IDENTITY
	,BreweryName NVARCHAR(255) NOT NULL
	,AddressID INT NOT NULL
		CONSTRAINT FK_Brewery_AddressID
		REFERENCES dbo.SSAddress(AddressID)
	,VenueID INT NOT NULL
		CONSTRAINT FK_Brewery_VenueID
		REFERENCES dbo.Venue(VenueID)
	,OpeningDate DATETIME NOT NULL
	,ClosingDate DATETIME
	)

CREATE TABLE dbo.Beer(
	BeerID INT NOT null
		CONSTRAINT PK_Beer
		PRIMARY KEY IDENTITY
	,BeerName NVARCHAR(255) NOT NULL
	,BeerTypeID INT NOT NULL
		CONSTRAINT FK_Beer_BeerTypeID
		REFERENCES ref.BeerType(BeerTypeID)
	)

/*

DROP TABLE dbo.Beer
DROP TABLE dbo.Brewery
DROP TABLE ref.BeerType
DROP TABLE ref.BeerFamily

*/